source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'LDZFCategories_Example' do
  pod 'LDZFCategories/UIKit', :path => '../'
  pod 'LDZFCategories/Foundation', :path => '../'

  pod 'LDZFCommon'
  target 'LDZFCategories_Tests' do
    inherit! :search_paths

    
  end
end
